# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    libopenblas-dev \
    liblapack-dev \
    libx11-dev \
    libgtk-3-dev \
    libboost-python-dev \
    && rm -rf /var/lib/apt/lists/*

# Install dlib
RUN pip install dlib

# Copy the requirements file into the container
COPY requirements.txt ./

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . /usr/src/app

# Set the working directory to the app directory
WORKDIR /usr/src/app/

# Run the encode_images script
RUN PYTHONPATH=$PYTHONPATH:$(pwd) python scripts/encode_images.py -i /usr/src/app/photos -o /usr/src/app/computed_faces.json --add-only

# Final stage to copy the results to the local working directory
FROM scratch AS final
COPY --from=0 /usr/src/app/computed_faces.json /computed_faces.json
COPY --from=0 /usr/src/app/photos/.skip_file /photos/.skip_file
COPY --from=0 /usr/src/app/backend/media/thumbs /backend/media/thumbs
